#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Balls
/* NOTE: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
 *       Several places expect the ball IDs to be first and contiguous (e.g. gBattlescriptsForBallThrow and MON_DATA_POKEBALL)
 *       If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_034 for example)
 */
#define ITEM_MASTER_BALL   (ITEM_NONE + 1)
#define ITEM_ULTRA_BALL    (ITEM_NONE + 2)
#define ITEM_GREAT_BALL    (ITEM_NONE + 3)
#define ITEM_POKE_BALL     (ITEM_NONE + 4)
#define ITEM_SAFARI_BALL   (ITEM_NONE + 5)
#define ITEM_NET_BALL      (ITEM_NONE + 6)
#define ITEM_DIVE_BALL     (ITEM_NONE + 7)
#define ITEM_NEST_BALL     (ITEM_NONE + 8)
#define ITEM_REPEAT_BALL   (ITEM_NONE + 9)
#define ITEM_TIMER_BALL    (ITEM_NONE + 10)
#define ITEM_LUXURY_BALL   (ITEM_NONE + 11)
#define ITEM_PREMIER_BALL  (ITEM_NONE + 12)

#define FIRST_BALL         ITEM_MASTER_BALL
#define LAST_BALL          ITEM_PREMIER_BALL


// Usable Items
#define ITEM_POTION        (LAST_BALL + 1)
#define ITEM_ANTIDOTE      (LAST_BALL + 2)
#define ITEM_BURN_HEAL     (LAST_BALL + 3)
#define ITEM_ICE_HEAL      (LAST_BALL + 4)
#define ITEM_AWAKENING     (LAST_BALL + 5)
#define ITEM_PARALYZE_HEAL (LAST_BALL + 6)
#define ITEM_FULL_RESTORE  (LAST_BALL + 7)
#define ITEM_MAX_POTION    (LAST_BALL + 8)
#define ITEM_HYPER_POTION  (LAST_BALL + 9)
#define ITEM_SUPER_POTION  (LAST_BALL + 10)
#define ITEM_FULL_HEAL     (LAST_BALL + 11)
#define ITEM_REVIVE        (LAST_BALL + 12)
#define ITEM_MAX_REVIVE    (LAST_BALL + 13)
#define ITEM_FRESH_WATER   (LAST_BALL + 14)
#define ITEM_SODA_POP      (LAST_BALL + 15)
#define ITEM_LEMONADE      (LAST_BALL + 16)
#define ITEM_MOOMOO_MILK   (LAST_BALL + 17)
#define ITEM_ENERGY_POWDER (LAST_BALL + 18)
#define ITEM_ENERGY_ROOT   (LAST_BALL + 19)
#define ITEM_HEAL_POWDER   (LAST_BALL + 20)
#define ITEM_REVIVAL_HERB  (LAST_BALL + 21)
#define ITEM_ETHER         (LAST_BALL + 22)
#define ITEM_MAX_ETHER     (LAST_BALL + 23)
#define ITEM_ELIXIR        (LAST_BALL + 24)
#define ITEM_MAX_ELIXIR    (LAST_BALL + 25)
#define ITEM_LAVA_COOKIE   (LAST_BALL + 26)
#define ITEM_BLUE_FLUTE    (LAST_BALL + 27)
#define ITEM_YELLOW_FLUTE  (LAST_BALL + 28)
#define ITEM_RED_FLUTE     (LAST_BALL + 29)
#define ITEM_BLACK_FLUTE   (LAST_BALL + 30)
#define ITEM_WHITE_FLUTE   (LAST_BALL + 31)
#define ITEM_BERRY_JUICE   (LAST_BALL + 32)
#define ITEM_SACRED_ASH    (LAST_BALL + 33)
#define ITEM_SHOAL_SALT    (LAST_BALL + 34)
#define ITEM_SHOAL_SHELL   (LAST_BALL + 35)
#define ITEM_RED_SHARD     (LAST_BALL + 36)
#define ITEM_BLUE_SHARD    (LAST_BALL + 37)
#define ITEM_YELLOW_SHARD  (LAST_BALL + 38)
#define ITEM_GREEN_SHARD   (LAST_BALL + 39)
#define ITEM_HP_UP         (LAST_BALL + 40)
#define ITEM_PROTEIN       (LAST_BALL + 41)
#define ITEM_IRON          (LAST_BALL + 42)
#define ITEM_CARBOS        (LAST_BALL + 43)
#define ITEM_CALCIUM       (LAST_BALL + 44)
#define ITEM_RARE_CANDY    (LAST_BALL + 45)
#define ITEM_PP_UP         (LAST_BALL + 46)
#define ITEM_ZINC          (LAST_BALL + 47)
#define ITEM_PP_MAX        (LAST_BALL + 48)
#define ITEM_GUARD_SPEC    (LAST_BALL + 49)
#define ITEM_DIRE_HIT      (LAST_BALL + 50)
#define ITEM_X_ATTACK      (LAST_BALL + 51)
#define ITEM_X_DEFEND      (LAST_BALL + 52)
#define ITEM_X_SPEED       (LAST_BALL + 53)
#define ITEM_X_ACCURACY    (LAST_BALL + 54)
#define ITEM_X_SPECIAL     (LAST_BALL + 55)
#define ITEM_POKE_DOLL     (LAST_BALL + 56)
#define ITEM_FLUFFY_TAIL   (LAST_BALL + 57)
#define ITEM_SUPER_REPEL   (LAST_BALL + 58)
#define ITEM_MAX_REPEL     (LAST_BALL + 59)
#define ITEM_ESCAPE_ROPE   (LAST_BALL + 60)
#define ITEM_REPEL         (LAST_BALL + 61)
#define ITEM_SUN_STONE     (LAST_BALL + 62)
#define ITEM_MOON_STONE    (LAST_BALL + 63)
#define ITEM_FIRE_STONE    (LAST_BALL + 64)
#define ITEM_THUNDER_STONE (LAST_BALL + 65)
#define ITEM_WATER_STONE   (LAST_BALL + 66)
#define ITEM_LEAF_STONE    (LAST_BALL + 67)

#define LAST_USABLE_ITEM   ITEM_LEAF_STONE


// Valuables
#define ITEM_TINY_MUSHROOM (LAST_USABLE_ITEM + 1)
#define ITEM_BIG_MUSHROOM  (LAST_USABLE_ITEM + 2)
#define ITEM_PEARL         (LAST_USABLE_ITEM + 3)
#define ITEM_BIG_PEARL     (LAST_USABLE_ITEM + 4)
#define ITEM_STARDUST      (LAST_USABLE_ITEM + 5)
#define ITEM_STAR_PIECE    (LAST_USABLE_ITEM + 6)
#define ITEM_NUGGET        (LAST_USABLE_ITEM + 7)
#define ITEM_HEART_SCALE   (LAST_USABLE_ITEM + 8)

#define LAST_VALUABLE_ITEM ITEM_HEART_SCALE


// Mails
#define ITEM_ORANGE_MAIL  (LAST_VALUABLE_ITEM + 1)
#define ITEM_HARBOR_MAIL  (LAST_VALUABLE_ITEM + 2)
#define ITEM_GLITTER_MAIL (LAST_VALUABLE_ITEM + 3)
#define ITEM_MECH_MAIL    (LAST_VALUABLE_ITEM + 4)
#define ITEM_WOOD_MAIL    (LAST_VALUABLE_ITEM + 5)
#define ITEM_WAVE_MAIL    (LAST_VALUABLE_ITEM + 6)
#define ITEM_BEAD_MAIL    (LAST_VALUABLE_ITEM + 7)
#define ITEM_SHADOW_MAIL  (LAST_VALUABLE_ITEM + 8)
#define ITEM_TROPIC_MAIL  (LAST_VALUABLE_ITEM + 9)
#define ITEM_DREAM_MAIL   (LAST_VALUABLE_ITEM + 10)
#define ITEM_FAB_MAIL     (LAST_VALUABLE_ITEM + 11)
#define ITEM_RETRO_MAIL   (LAST_VALUABLE_ITEM + 12)

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL // See #define ITEM_TO_MAIL
#define LAST_MAIL_ITEM    ITEM_RETRO_MAIL


// Berries
#define ITEM_CHERI_BERRY  (LAST_MAIL_ITEM + 1)
#define ITEM_CHESTO_BERRY (LAST_MAIL_ITEM + 2)
#define ITEM_PECHA_BERRY  (LAST_MAIL_ITEM + 3)
#define ITEM_RAWST_BERRY  (LAST_MAIL_ITEM + 4)
#define ITEM_ASPEAR_BERRY (LAST_MAIL_ITEM + 5)
#define ITEM_LEPPA_BERRY  (LAST_MAIL_ITEM + 6)
#define ITEM_ORAN_BERRY   (LAST_MAIL_ITEM + 7)
#define ITEM_PERSIM_BERRY (LAST_MAIL_ITEM + 8)
#define ITEM_LUM_BERRY    (LAST_MAIL_ITEM + 9)
#define ITEM_SITRUS_BERRY (LAST_MAIL_ITEM + 10)
#define ITEM_FIGY_BERRY   (LAST_MAIL_ITEM + 11)
#define ITEM_WIKI_BERRY   (LAST_MAIL_ITEM + 12)
#define ITEM_MAGO_BERRY   (LAST_MAIL_ITEM + 13)
#define ITEM_AGUAV_BERRY  (LAST_MAIL_ITEM + 14)
#define ITEM_IAPAPA_BERRY (LAST_MAIL_ITEM + 15)
#define ITEM_RAZZ_BERRY   (LAST_MAIL_ITEM + 16)
#define ITEM_BLUK_BERRY   (LAST_MAIL_ITEM + 17)
#define ITEM_NANAB_BERRY  (LAST_MAIL_ITEM + 18)
#define ITEM_WEPEAR_BERRY (LAST_MAIL_ITEM + 19)
#define ITEM_PINAP_BERRY  (LAST_MAIL_ITEM + 20)
#define ITEM_POMEG_BERRY  (LAST_MAIL_ITEM + 21)
#define ITEM_KELPSY_BERRY (LAST_MAIL_ITEM + 22)
#define ITEM_QUALOT_BERRY (LAST_MAIL_ITEM + 23)
#define ITEM_HONDEW_BERRY (LAST_MAIL_ITEM + 24)
#define ITEM_GREPA_BERRY  (LAST_MAIL_ITEM + 25)
#define ITEM_TAMATO_BERRY (LAST_MAIL_ITEM + 26)
#define ITEM_CORNN_BERRY  (LAST_MAIL_ITEM + 27)
#define ITEM_MAGOST_BERRY (LAST_MAIL_ITEM + 28)
#define ITEM_RABUTA_BERRY (LAST_MAIL_ITEM + 29)
#define ITEM_NOMEL_BERRY  (LAST_MAIL_ITEM + 30)
#define ITEM_SPELON_BERRY (LAST_MAIL_ITEM + 31)
#define ITEM_PAMTRE_BERRY (LAST_MAIL_ITEM + 32)
#define ITEM_WATMEL_BERRY (LAST_MAIL_ITEM + 33)
#define ITEM_DURIN_BERRY  (LAST_MAIL_ITEM + 34)
#define ITEM_BELUE_BERRY  (LAST_MAIL_ITEM + 35)
#define ITEM_LIECHI_BERRY (LAST_MAIL_ITEM + 36)
#define ITEM_GANLON_BERRY (LAST_MAIL_ITEM + 37)
#define ITEM_SALAC_BERRY  (LAST_MAIL_ITEM + 38)
#define ITEM_PETAYA_BERRY (LAST_MAIL_ITEM + 39)
#define ITEM_APICOT_BERRY (LAST_MAIL_ITEM + 40)
#define ITEM_LANSAT_BERRY (LAST_MAIL_ITEM + 41)
#define ITEM_STARF_BERRY  (LAST_MAIL_ITEM + 42)
#define ITEM_ENIGMA_BERRY (LAST_MAIL_ITEM + 43)

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY

#define ITEM_UNUSED_BERRY_1 (LAST_BERRY_INDEX + 1)
#define ITEM_UNUSED_BERRY_2 (LAST_BERRY_INDEX + 2)
#define ITEM_UNUSED_BERRY_3 (LAST_BERRY_INDEX + 3)

#define MAX_BERRY_INDEX ITEM_UNUSED_BERRY_3
#define LAST_BERRY_ITEM ITEM_UNUSED_BERRY_3 // Bit redundant, but like it for formatting


// Battle Held items
#define ITEM_BRIGHT_POWDER  (LAST_BERRY_ITEM + 1)
#define ITEM_WHITE_HERB     (LAST_BERRY_ITEM + 2)
#define ITEM_MACHO_BRACE    (LAST_BERRY_ITEM + 3)
#define ITEM_EXP_SHARE      (LAST_BERRY_ITEM + 4)
#define ITEM_QUICK_CLAW     (LAST_BERRY_ITEM + 5)
#define ITEM_SOOTHE_BELL    (LAST_BERRY_ITEM + 6)
#define ITEM_MENTAL_HERB    (LAST_BERRY_ITEM + 7)
#define ITEM_CHOICE_BAND    (LAST_BERRY_ITEM + 8)
#define ITEM_KINGS_ROCK     (LAST_BERRY_ITEM + 9)
#define ITEM_SILVER_POWDER  (LAST_BERRY_ITEM + 10)
#define ITEM_AMULET_COIN    (LAST_BERRY_ITEM + 11)
#define ITEM_CLEANSE_TAG    (LAST_BERRY_ITEM + 12)
#define ITEM_SOUL_DEW       (LAST_BERRY_ITEM + 13)
#define ITEM_DEEP_SEA_TOOTH (LAST_BERRY_ITEM + 14)
#define ITEM_DEEP_SEA_SCALE (LAST_BERRY_ITEM + 15)
#define ITEM_SMOKE_BALL     (LAST_BERRY_ITEM + 16)
#define ITEM_EVERSTONE      (LAST_BERRY_ITEM + 17)
#define ITEM_FOCUS_BAND     (LAST_BERRY_ITEM + 18)
#define ITEM_LUCKY_EGG      (LAST_BERRY_ITEM + 19)
#define ITEM_SCOPE_LENS     (LAST_BERRY_ITEM + 20)
#define ITEM_METAL_COAT     (LAST_BERRY_ITEM + 21)
#define ITEM_LEFTOVERS      (LAST_BERRY_ITEM + 22)
#define ITEM_DRAGON_SCALE   (LAST_BERRY_ITEM + 23)
#define ITEM_LIGHT_BALL     (LAST_BERRY_ITEM + 24)
#define ITEM_SOFT_SAND      (LAST_BERRY_ITEM + 25)
#define ITEM_HARD_STONE     (LAST_BERRY_ITEM + 26)
#define ITEM_MIRACLE_SEED   (LAST_BERRY_ITEM + 27)
#define ITEM_BLACK_GLASSES  (LAST_BERRY_ITEM + 28)
#define ITEM_BLACK_BELT     (LAST_BERRY_ITEM + 29)
#define ITEM_MAGNET         (LAST_BERRY_ITEM + 30)
#define ITEM_MYSTIC_WATER   (LAST_BERRY_ITEM + 31)
#define ITEM_SHARP_BEAK     (LAST_BERRY_ITEM + 32)
#define ITEM_POISON_BARB    (LAST_BERRY_ITEM + 33)
#define ITEM_NEVER_MELT_ICE (LAST_BERRY_ITEM + 34)
#define ITEM_SPELL_TAG      (LAST_BERRY_ITEM + 35)
#define ITEM_TWISTED_SPOON  (LAST_BERRY_ITEM + 36)
#define ITEM_CHARCOAL       (LAST_BERRY_ITEM + 37)
#define ITEM_DRAGON_FANG    (LAST_BERRY_ITEM + 38)
#define ITEM_SILK_SCARF     (LAST_BERRY_ITEM + 39)
#define ITEM_UP_GRADE       (LAST_BERRY_ITEM + 40)
#define ITEM_SHELL_BELL     (LAST_BERRY_ITEM + 41)
#define ITEM_SEA_INCENSE    (LAST_BERRY_ITEM + 42)
#define ITEM_LAX_INCENSE    (LAST_BERRY_ITEM + 43)
#define ITEM_LUCKY_PUNCH    (LAST_BERRY_ITEM + 44)
#define ITEM_METAL_POWDER   (LAST_BERRY_ITEM + 45)
#define ITEM_THICK_CLUB     (LAST_BERRY_ITEM + 46)
#define ITEM_STICK          (LAST_BERRY_ITEM + 47)

#define LAST_HELD_ITEM      ITEM_STICK


// Contest held items
#define ITEM_RED_SCARF    (LAST_HELD_ITEM + 1)
#define ITEM_BLUE_SCARF   (LAST_HELD_ITEM + 2)
#define ITEM_PINK_SCARF   (LAST_HELD_ITEM + 3)
#define ITEM_GREEN_SCARF  (LAST_HELD_ITEM + 4)
#define ITEM_YELLOW_SCARF (LAST_HELD_ITEM + 5)

#define LAST_SCARF_ITEM   ITEM_YELLOW_SCARF
 
// Key Items
#define ITEM_MACH_BIKE      (LAST_SCARF_ITEM + 1)
#define ITEM_COIN_CASE      (LAST_SCARF_ITEM + 2)
#define ITEM_ITEMFINDER     (LAST_SCARF_ITEM + 3)
#define ITEM_OLD_ROD        (LAST_SCARF_ITEM + 4)
#define ITEM_GOOD_ROD       (LAST_SCARF_ITEM + 5)
#define ITEM_SUPER_ROD      (LAST_SCARF_ITEM + 6)
#define ITEM_SS_TICKET      (LAST_SCARF_ITEM + 7)
#define ITEM_CONTEST_PASS   (LAST_SCARF_ITEM + 8)
#define ITEM_WAILMER_PAIL   (LAST_SCARF_ITEM + 9)
#define ITEM_DEVON_GOODS    (LAST_SCARF_ITEM + 10)
#define ITEM_SOOT_SACK      (LAST_SCARF_ITEM + 11)
#define ITEM_BASEMENT_KEY   (LAST_SCARF_ITEM + 12)
#define ITEM_ACRO_BIKE      (LAST_SCARF_ITEM + 13)
#define ITEM_POKEBLOCK_CASE (LAST_SCARF_ITEM + 14)
#define ITEM_LETTER         (LAST_SCARF_ITEM + 15)
#define ITEM_EON_TICKET     (LAST_SCARF_ITEM + 16)
#define ITEM_RED_ORB        (LAST_SCARF_ITEM + 17)
#define ITEM_BLUE_ORB       (LAST_SCARF_ITEM + 18)
#define ITEM_SCANNER        (LAST_SCARF_ITEM + 19)
#define ITEM_GO_GOGGLES     (LAST_SCARF_ITEM + 20)
#define ITEM_METEORITE      (LAST_SCARF_ITEM + 21)
#define ITEM_ROOM_1_KEY     (LAST_SCARF_ITEM + 22)
#define ITEM_ROOM_2_KEY     (LAST_SCARF_ITEM + 23)
#define ITEM_ROOM_4_KEY     (LAST_SCARF_ITEM + 24)
#define ITEM_ROOM_6_KEY     (LAST_SCARF_ITEM + 25)
#define ITEM_STORAGE_KEY    (LAST_SCARF_ITEM + 26)
#define ITEM_ROOT_FOSSIL    (LAST_SCARF_ITEM + 27)
#define ITEM_CLAW_FOSSIL    (LAST_SCARF_ITEM + 28)
#define ITEM_DEVON_SCOPE    (LAST_SCARF_ITEM + 29)

#define LAST_KEY_ITEM       ITEM_DEVON_SCOPE

// TMs/HMs
#define ITEM_TM01 (LAST_KEY_ITEM + 1)
#define ITEM_TM02 (LAST_KEY_ITEM + 2)
#define ITEM_TM03 (LAST_KEY_ITEM + 3)
#define ITEM_TM04 (LAST_KEY_ITEM + 4)
#define ITEM_TM05 (LAST_KEY_ITEM + 5)
#define ITEM_TM06 (LAST_KEY_ITEM + 6)
#define ITEM_TM07 (LAST_KEY_ITEM + 7)
#define ITEM_TM08 (LAST_KEY_ITEM + 8)
#define ITEM_TM09 (LAST_KEY_ITEM + 9)
#define ITEM_TM10 (LAST_KEY_ITEM + 10)
#define ITEM_TM11 (LAST_KEY_ITEM + 11)
#define ITEM_TM12 (LAST_KEY_ITEM + 12)
#define ITEM_TM13 (LAST_KEY_ITEM + 13)
#define ITEM_TM14 (LAST_KEY_ITEM + 14)
#define ITEM_TM15 (LAST_KEY_ITEM + 15)
#define ITEM_TM16 (LAST_KEY_ITEM + 16)
#define ITEM_TM17 (LAST_KEY_ITEM + 17)
#define ITEM_TM18 (LAST_KEY_ITEM + 18)
#define ITEM_TM19 (LAST_KEY_ITEM + 19)
#define ITEM_TM20 (LAST_KEY_ITEM + 20)
#define ITEM_TM21 (LAST_KEY_ITEM + 21)
#define ITEM_TM22 (LAST_KEY_ITEM + 22)
#define ITEM_TM23 (LAST_KEY_ITEM + 23)
#define ITEM_TM24 (LAST_KEY_ITEM + 24)
#define ITEM_TM25 (LAST_KEY_ITEM + 25)
#define ITEM_TM26 (LAST_KEY_ITEM + 26)
#define ITEM_TM27 (LAST_KEY_ITEM + 27)
#define ITEM_TM28 (LAST_KEY_ITEM + 28)
#define ITEM_TM29 (LAST_KEY_ITEM + 29)
#define ITEM_TM30 (LAST_KEY_ITEM + 30)
#define ITEM_TM31 (LAST_KEY_ITEM + 31)
#define ITEM_TM32 (LAST_KEY_ITEM + 32)
#define ITEM_TM33 (LAST_KEY_ITEM + 33)
#define ITEM_TM34 (LAST_KEY_ITEM + 34)
#define ITEM_TM35 (LAST_KEY_ITEM + 35)
#define ITEM_TM36 (LAST_KEY_ITEM + 36)
#define ITEM_TM37 (LAST_KEY_ITEM + 37)
#define ITEM_TM38 (LAST_KEY_ITEM + 38)
#define ITEM_TM39 (LAST_KEY_ITEM + 39)
#define ITEM_TM40 (LAST_KEY_ITEM + 40)
#define ITEM_TM41 (LAST_KEY_ITEM + 41)
#define ITEM_TM42 (LAST_KEY_ITEM + 42)
#define ITEM_TM43 (LAST_KEY_ITEM + 43)
#define ITEM_TM44 (LAST_KEY_ITEM + 44)
#define ITEM_TM45 (LAST_KEY_ITEM + 45)
#define ITEM_TM46 (LAST_KEY_ITEM + 46)
#define ITEM_TM47 (LAST_KEY_ITEM + 47)
#define ITEM_TM48 (LAST_KEY_ITEM + 48)
#define ITEM_TM49 (LAST_KEY_ITEM + 49)
#define ITEM_TM50 (LAST_KEY_ITEM + 50)
#define ITEM_HM01 (LAST_KEY_ITEM + 51)
#define ITEM_HM02 (LAST_KEY_ITEM + 52)
#define ITEM_HM03 (LAST_KEY_ITEM + 53)
#define ITEM_HM04 (LAST_KEY_ITEM + 54)
#define ITEM_HM05 (LAST_KEY_ITEM + 55)
#define ITEM_HM06 (LAST_KEY_ITEM + 56)
#define ITEM_HM07 (LAST_KEY_ITEM + 57)
#define ITEM_HM08 (LAST_KEY_ITEM + 58)

#define LAST_TM_HM_ITEM ITEM_HM08


// FireRed/LeafGreen
#define ITEM_OAKS_PARCEL   (LAST_TM_HM_ITEM + 1)
#define ITEM_POKE_FLUTE    (LAST_TM_HM_ITEM + 2)
#define ITEM_SECRET_KEY    (LAST_TM_HM_ITEM + 3)
#define ITEM_BIKE_VOUCHER  (LAST_TM_HM_ITEM + 4)
#define ITEM_GOLD_TEETH    (LAST_TM_HM_ITEM + 5)
#define ITEM_OLD_AMBER     (LAST_TM_HM_ITEM + 6)
#define ITEM_CARD_KEY      (LAST_TM_HM_ITEM + 7)
#define ITEM_LIFT_KEY      (LAST_TM_HM_ITEM + 8)
#define ITEM_HELIX_FOSSIL  (LAST_TM_HM_ITEM + 9)
#define ITEM_DOME_FOSSIL   (LAST_TM_HM_ITEM + 10)
#define ITEM_SILPH_SCOPE   (LAST_TM_HM_ITEM + 11)
#define ITEM_BICYCLE       (LAST_TM_HM_ITEM + 12)
#define ITEM_TOWN_MAP      (LAST_TM_HM_ITEM + 13)
#define ITEM_VS_SEEKER     (LAST_TM_HM_ITEM + 14)
#define ITEM_FAME_CHECKER  (LAST_TM_HM_ITEM + 15)
#define ITEM_TM_CASE       (LAST_TM_HM_ITEM + 16)
#define ITEM_BERRY_POUCH   (LAST_TM_HM_ITEM + 17)
#define ITEM_TEACHY_TV     (LAST_TM_HM_ITEM + 18)
#define ITEM_TRI_PASS      (LAST_TM_HM_ITEM + 19)
#define ITEM_RAINBOW_PASS  (LAST_TM_HM_ITEM + 20)
#define ITEM_TEA           (LAST_TM_HM_ITEM + 21)
#define ITEM_MYSTIC_TICKET (LAST_TM_HM_ITEM + 22)
#define ITEM_AURORA_TICKET (LAST_TM_HM_ITEM + 23)
#define ITEM_POWDER_JAR    (LAST_TM_HM_ITEM + 24)
#define ITEM_RUBY          (LAST_TM_HM_ITEM + 25)
#define ITEM_SAPPHIRE      (LAST_TM_HM_ITEM + 26)

#define LAST_FRLG_ITEM     ITEM_SAPPHIRE

// Emerald
#define ITEM_MAGMA_EMBLEM (LAST_FRLG_ITEM + 1)
#define ITEM_OLD_SEA_MAP  (LAST_FRLG_ITEM + 2)

#define LAST_EMERALD_ITEM ITEM_OLD_SEA_MAP

#define LAST_ITEM   LAST_EMERALD_ITEM
#define ITEMS_COUNT (LAST_ITEM + 1)

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF

#define NUM_TECHNICAL_MACHINES 50
#define NUM_HIDDEN_MACHINES     8

#define MAX_BAG_ITEM_CAPACITY  99
#define MAX_PC_ITEM_CAPACITY   999
#define MAX_BERRY_CAPACITY     999

#define BAG_ITEM_CAPACITY_DIGITS 2
#define BERRY_CAPACITY_DIGITS 3
#define MAX_ITEM_DIGITS BERRY_CAPACITY_DIGITS

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL        0
#define ITEM_USE_PARTY_MENU  1
#define ITEM_USE_FIELD       2
#define ITEM_USE_PBLOCK_CASE 3
#define ITEM_USE_BAG_MENU    4 // No exit callback, stays in bag menu

// Item battle usage IDs (only checked to see if nonzero)
#define ITEM_B_USE_MEDICINE 1
#define ITEM_B_USE_OTHER    2

// Check if the item is one that can be used on a Pokémon.
#define ITEM_HAS_EFFECT(item) ((item) >= ITEM_POTION && (item) <= MAX_BERRY_INDEX)

#endif  // GUARD_CONSTANTS_ITEMS_H
